// Lista completa de países com códigos DDI e formatação de telefone
export interface Country {
    code: string;
    name: string;
    flag: string;
    ddi: string;
    placeholder: string;
}

export const COUNTRIES: Country[] = [
    // Países prioritários (mais usados)
    { code: 'BR', name: 'Brasil', flag: '🇧🇷', ddi: '+55', placeholder: '(DDD) Número' },
    { code: 'PT', name: 'Portugal', flag: '🇵🇹', ddi: '+351', placeholder: 'Número' },
    { code: 'US', name: 'Estados Unidos', flag: '🇺🇸', ddi: '+1', placeholder: '(Area) Number' },
    { code: 'AO', name: 'Angola', flag: '🇦🇴', ddi: '+244', placeholder: 'Número' },
    { code: 'MZ', name: 'Moçambique', flag: '🇲🇿', ddi: '+258', placeholder: 'Número' },
    { code: 'ES', name: 'Espanha', flag: '🇪🇸', ddi: '+34', placeholder: 'Número' },
    { code: 'FR', name: 'França', flag: '🇫🇷', ddi: '+33', placeholder: 'Número' },
    { code: 'GB', name: 'Reino Unido', flag: '🇬🇧', ddi: '+44', placeholder: 'Número' },
    { code: 'IT', name: 'Itália', flag: '🇮🇹', ddi: '+39', placeholder: 'Número' },
    { code: 'DE', name: 'Alemanha', flag: '🇩🇪', ddi: '+49', placeholder: 'Número' },
    { code: 'CA', name: 'Canadá', flag: '🇨🇦', ddi: '+1', placeholder: '(Area) Number' },
    { code: 'AR', name: 'Argentina', flag: '🇦🇷', ddi: '+54', placeholder: 'Número' },
    { code: 'CH', name: 'Suíça', flag: '🇨🇭', ddi: '+41', placeholder: 'Número' },
    { code: 'AU', name: 'Austrália', flag: '🇦🇺', ddi: '+61', placeholder: 'Número' },

    // Resto dos países em ordem alfabética
    { code: 'AF', name: 'Afeganistão', flag: '🇦🇫', ddi: '+93', placeholder: 'Número' },
    { code: 'ZA', name: 'África do Sul', flag: '🇿🇦', ddi: '+27', placeholder: 'Número' },
    { code: 'AL', name: 'Albânia', flag: '🇦🇱', ddi: '+355', placeholder: 'Número' },
    { code: 'DZ', name: 'Argélia', flag: '🇩🇿', ddi: '+213', placeholder: 'Número' },
    { code: 'AD', name: 'Andorra', flag: '🇦🇩', ddi: '+376', placeholder: 'Número' },
    { code: 'SA', name: 'Arábia Saudita', flag: '🇸🇦', ddi: '+966', placeholder: 'Número' },
    { code: 'AM', name: 'Armênia', flag: '🇦🇲', ddi: '+374', placeholder: 'Número' },
    { code: 'AT', name: 'Áustria', flag: '🇦🇹', ddi: '+43', placeholder: 'Número' },
    { code: 'AZ', name: 'Azerbaijão', flag: '🇦🇿', ddi: '+994', placeholder: 'Número' },
    { code: 'BS', name: 'Bahamas', flag: '🇧🇸', ddi: '+1-242', placeholder: 'Número' },
    { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', ddi: '+880', placeholder: 'Número' },
    { code: 'BB', name: 'Barbados', flag: '🇧🇧', ddi: '+1-246', placeholder: 'Número' },
    { code: 'BH', name: 'Bahrein', flag: '🇧🇭', ddi: '+973', placeholder: 'Número' },
    { code: 'BY', name: 'Belarus', flag: '🇧🇾', ddi: '+375', placeholder: 'Número' },
    { code: 'BE', name: 'Bélgica', flag: '🇧🇪', ddi: '+32', placeholder: 'Número' },
    { code: 'BZ', name: 'Belize', flag: '🇧🇿', ddi: '+501', placeholder: 'Número' },
    { code: 'BJ', name: 'Benin', flag: '🇧🇯', ddi: '+229', placeholder: 'Número' },
    { code: 'BO', name: 'Bolívia', flag: '🇧🇴', ddi: '+591', placeholder: 'Número' },
    { code: 'BA', name: 'Bósnia e Herzegovina', flag: '🇧🇦', ddi: '+387', placeholder: 'Número' },
    { code: 'BW', name: 'Botswana', flag: '🇧🇼', ddi: '+267', placeholder: 'Número' },
    { code: 'BN', name: 'Brunei', flag: '🇧🇳', ddi: '+673', placeholder: 'Número' },
    { code: 'BG', name: 'Bulgária', flag: '🇧🇬', ddi: '+359', placeholder: 'Número' },
    { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', ddi: '+226', placeholder: 'Número' },
    { code: 'BI', name: 'Burundi', flag: '🇧🇮', ddi: '+257', placeholder: 'Número' },
    { code: 'BT', name: 'Butão', flag: '🇧🇹', ddi: '+975', placeholder: 'Número' },
    { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', ddi: '+238', placeholder: 'Número' },
    { code: 'CM', name: 'Camarões', flag: '🇨🇲', ddi: '+237', placeholder: 'Número' },
    { code: 'KH', name: 'Camboja', flag: '🇰🇭', ddi: '+855', placeholder: 'Número' },
    { code: 'QA', name: 'Catar', flag: '🇶🇦', ddi: '+974', placeholder: 'Número' },
    { code: 'KZ', name: 'Cazaquistão', flag: '🇰🇿', ddi: '+7', placeholder: 'Número' },
    { code: 'TD', name: 'Chade', flag: '🇹🇩', ddi: '+235', placeholder: 'Número' },
    { code: 'CL', name: 'Chile', flag: '🇨🇱', ddi: '+56', placeholder: 'Número' },
    { code: 'CN', name: 'China', flag: '🇨🇳', ddi: '+86', placeholder: 'Número' },
    { code: 'CY', name: 'Chipre', flag: '🇨🇾', ddi: '+357', placeholder: 'Número' },
    { code: 'CO', name: 'Colômbia', flag: '🇨🇴', ddi: '+57', placeholder: 'Número' },
    { code: 'KM', name: 'Comores', flag: '🇰🇲', ddi: '+269', placeholder: 'Número' },
    { code: 'CG', name: 'Congo', flag: '🇨🇬', ddi: '+242', placeholder: 'Número' },
    { code: 'CD', name: 'Congo (RDC)', flag: '🇨🇩', ddi: '+243', placeholder: 'Número' },
    { code: 'KP', name: 'Coreia do Norte', flag: '🇰🇵', ddi: '+850', placeholder: 'Número' },
    { code: 'KR', name: 'Coreia do Sul', flag: '🇰🇷', ddi: '+82', placeholder: 'Número' },
    { code: 'CI', name: 'Costa do Marfim', flag: '🇨🇮', ddi: '+225', placeholder: 'Número' },
    { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', ddi: '+506', placeholder: 'Número' },
    { code: 'HR', name: 'Croácia', flag: '🇭🇷', ddi: '+385', placeholder: 'Número' },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺', ddi: '+53', placeholder: 'Número' },
    { code: 'DK', name: 'Dinamarca', flag: '🇩🇰', ddi: '+45', placeholder: 'Número' },
    { code: 'DJ', name: 'Djibuti', flag: '🇩🇯', ddi: '+253', placeholder: 'Número' },
    { code: 'DM', name: 'Dominica', flag: '🇩🇲', ddi: '+1-767', placeholder: 'Número' },
    { code: 'EG', name: 'Egito', flag: '🇪🇬', ddi: '+20', placeholder: 'Número' },
    { code: 'SV', name: 'El Salvador', flag: '🇸🇻', ddi: '+503', placeholder: 'Número' },
    { code: 'AE', name: 'Emirados Árabes', flag: '🇦🇪', ddi: '+971', placeholder: 'Número' },
    { code: 'EC', name: 'Equador', flag: '🇪🇨', ddi: '+593', placeholder: 'Número' },
    { code: 'ER', name: 'Eritreia', flag: '🇪🇷', ddi: '+291', placeholder: 'Número' },
    { code: 'SK', name: 'Eslováquia', flag: '🇸🇰', ddi: '+421', placeholder: 'Número' },
    { code: 'SI', name: 'Eslovênia', flag: '🇸🇮', ddi: '+386', placeholder: 'Número' },
    { code: 'EE', name: 'Estônia', flag: '🇪🇪', ddi: '+372', placeholder: 'Número' },
    { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', ddi: '+268', placeholder: 'Número' },
    { code: 'ET', name: 'Etiópia', flag: '🇪🇹', ddi: '+251', placeholder: 'Número' },
    { code: 'FJ', name: 'Fiji', flag: '🇫🇯', ddi: '+679', placeholder: 'Número' },
    { code: 'PH', name: 'Filipinas', flag: '🇵🇭', ddi: '+63', placeholder: 'Número' },
    { code: 'FI', name: 'Finlândia', flag: '🇫🇮', ddi: '+358', placeholder: 'Número' },
    { code: 'GA', name: 'Gabão', flag: '🇬🇦', ddi: '+241', placeholder: 'Número' },
    { code: 'GM', name: 'Gâmbia', flag: '🇬🇲', ddi: '+220', placeholder: 'Número' },
    { code: 'GH', name: 'Gana', flag: '🇬🇭', ddi: '+233', placeholder: 'Número' },
    { code: 'GE', name: 'Geórgia', flag: '🇬🇪', ddi: '+995', placeholder: 'Número' },
    { code: 'GR', name: 'Grécia', flag: '🇬🇷', ddi: '+30', placeholder: 'Número' },
    { code: 'GD', name: 'Granada', flag: '🇬🇩', ddi: '+1-473', placeholder: 'Número' },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹', ddi: '+502', placeholder: 'Número' },
    { code: 'GY', name: 'Guiana', flag: '🇬🇾', ddi: '+592', placeholder: 'Número' },
    { code: 'GN', name: 'Guiné', flag: '🇬🇳', ddi: '+224', placeholder: 'Número' },
    { code: 'GQ', name: 'Guiné Equatorial', flag: '🇬🇶', ddi: '+240', placeholder: 'Número' },
    { code: 'GW', name: 'Guiné-Bissau', flag: '🇬🇼', ddi: '+245', placeholder: 'Número' },
    { code: 'HT', name: 'Haiti', flag: '🇭🇹', ddi: '+509', placeholder: 'Número' },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳', ddi: '+504', placeholder: 'Número' },
    { code: 'HU', name: 'Hungria', flag: '🇭🇺', ddi: '+36', placeholder: 'Número' },
    { code: 'YE', name: 'Iêmen', flag: '🇾🇪', ddi: '+967', placeholder: 'Número' },
    { code: 'IN', name: 'Índia', flag: '🇮🇳', ddi: '+91', placeholder: 'Número' },
    { code: 'ID', name: 'Indonésia', flag: '🇮🇩', ddi: '+62', placeholder: 'Número' },
    { code: 'IR', name: 'Irã', flag: '🇮🇷', ddi: '+98', placeholder: 'Número' },
    { code: 'IQ', name: 'Iraque', flag: '🇮🇶', ddi: '+964', placeholder: 'Número' },
    { code: 'IE', name: 'Irlanda', flag: '🇮🇪', ddi: '+353', placeholder: 'Número' },
    { code: 'IS', name: 'Islândia', flag: '🇮🇸', ddi: '+354', placeholder: 'Número' },
    { code: 'IL', name: 'Israel', flag: '🇮🇱', ddi: '+972', placeholder: 'Número' },
    { code: 'JM', name: 'Jamaica', flag: '🇯🇲', ddi: '+1-876', placeholder: 'Número' },
    { code: 'JP', name: 'Japão', flag: '🇯🇵', ddi: '+81', placeholder: 'Número' },
    { code: 'JO', name: 'Jordânia', flag: '🇯🇴', ddi: '+962', placeholder: 'Número' },
    { code: 'KW', name: 'Kuwait', flag: '🇰🇼', ddi: '+965', placeholder: 'Número' },
    { code: 'LA', name: 'Laos', flag: '🇱🇦', ddi: '+856', placeholder: 'Número' },
    { code: 'LS', name: 'Lesoto', flag: '🇱🇸', ddi: '+266', placeholder: 'Número' },
    { code: 'LV', name: 'Letônia', flag: '🇱🇻', ddi: '+371', placeholder: 'Número' },
    { code: 'LB', name: 'Líbano', flag: '🇱🇧', ddi: '+961', placeholder: 'Número' },
    { code: 'LR', name: 'Libéria', flag: '🇱🇷', ddi: '+231', placeholder: 'Número' },
    { code: 'LY', name: 'Líbia', flag: '🇱🇾', ddi: '+218', placeholder: 'Número' },
    { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', ddi: '+423', placeholder: 'Número' },
    { code: 'LT', name: 'Lituânia', flag: '🇱🇹', ddi: '+370', placeholder: 'Número' },
    { code: 'LU', name: 'Luxemburgo', flag: '🇱🇺', ddi: '+352', placeholder: 'Número' },
    { code: 'MK', name: 'Macedônia do Norte', flag: '🇲🇰', ddi: '+389', placeholder: 'Número' },
    { code: 'MG', name: 'Madagascar', flag: '🇲🇬', ddi: '+261', placeholder: 'Número' },
    { code: 'MY', name: 'Malásia', flag: '🇲🇾', ddi: '+60', placeholder: 'Número' },
    { code: 'MW', name: 'Malawi', flag: '🇲🇼', ddi: '+265', placeholder: 'Número' },
    { code: 'MV', name: 'Maldivas', flag: '🇲🇻', ddi: '+960', placeholder: 'Número' },
    { code: 'ML', name: 'Mali', flag: '🇲🇱', ddi: '+223', placeholder: 'Número' },
    { code: 'MT', name: 'Malta', flag: '🇲🇹', ddi: '+356', placeholder: 'Número' },
    { code: 'MA', name: 'Marrocos', flag: '🇲🇦', ddi: '+212', placeholder: 'Número' },
    { code: 'MU', name: 'Maurício', flag: '🇲🇺', ddi: '+230', placeholder: 'Número' },
    { code: 'MR', name: 'Mauritânia', flag: '🇲🇷', ddi: '+222', placeholder: 'Número' },
    { code: 'MX', name: 'México', flag: '🇲🇽', ddi: '+52', placeholder: 'Número' },
    { code: 'MM', name: 'Mianmar', flag: '🇲🇲', ddi: '+95', placeholder: 'Número' },
    { code: 'FM', name: 'Micronésia', flag: '🇫🇲', ddi: '+691', placeholder: 'Número' },
    { code: 'MD', name: 'Moldávia', flag: '🇲🇩', ddi: '+373', placeholder: 'Número' },
    { code: 'MC', name: 'Mônaco', flag: '🇲🇨', ddi: '+377', placeholder: 'Número' },
    { code: 'MN', name: 'Mongólia', flag: '🇲🇳', ddi: '+976', placeholder: 'Número' },
    { code: 'ME', name: 'Montenegro', flag: '🇲🇪', ddi: '+382', placeholder: 'Número' },
    { code: 'NA', name: 'Namíbia', flag: '🇳🇦', ddi: '+264', placeholder: 'Número' },
    { code: 'NR', name: 'Nauru', flag: '🇳🇷', ddi: '+674', placeholder: 'Número' },
    { code: 'NP', name: 'Nepal', flag: '🇳🇵', ddi: '+977', placeholder: 'Número' },
    { code: 'NI', name: 'Nicarágua', flag: '🇳🇮', ddi: '+505', placeholder: 'Número' },
    { code: 'NE', name: 'Níger', flag: '🇳🇪', ddi: '+227', placeholder: 'Número' },
    { code: 'NG', name: 'Nigéria', flag: '🇳🇬', ddi: '+234', placeholder: 'Número' },
    { code: 'NO', name: 'Noruega', flag: '🇳🇴', ddi: '+47', placeholder: 'Número' },
    { code: 'NZ', name: 'Nova Zelândia', flag: '🇳🇿', ddi: '+64', placeholder: 'Número' },
    { code: 'OM', name: 'Omã', flag: '🇴🇲', ddi: '+968', placeholder: 'Número' },
    { code: 'NL', name: 'Países Baixos', flag: '🇳🇱', ddi: '+31', placeholder: 'Número' },
    { code: 'PW', name: 'Palau', flag: '🇵🇼', ddi: '+680', placeholder: 'Número' },
    { code: 'PA', name: 'Panamá', flag: '🇵🇦', ddi: '+507', placeholder: 'Número' },
    { code: 'PG', name: 'Papua-Nova Guiné', flag: '🇵🇬', ddi: '+675', placeholder: 'Número' },
    { code: 'PK', name: 'Paquistão', flag: '🇵🇰', ddi: '+92', placeholder: 'Número' },
    { code: 'PY', name: 'Paraguai', flag: '🇵🇾', ddi: '+595', placeholder: 'Número' },
    { code: 'PE', name: 'Peru', flag: '🇵🇪', ddi: '+51', placeholder: 'Número' },
    { code: 'PL', name: 'Polônia', flag: '🇵🇱', ddi: '+48', placeholder: 'Número' },
    { code: 'QA', name: 'Catar', flag: '🇶🇦', ddi: '+974', placeholder: 'Número' },
    { code: 'KE', name: 'Quênia', flag: '🇰🇪', ddi: '+254', placeholder: 'Número' },
    { code: 'KG', name: 'Quirguistão', flag: '🇰🇬', ddi: '+996', placeholder: 'Número' },
    { code: 'CF', name: 'República Centro-Africana', flag: '🇨🇫', ddi: '+236', placeholder: 'Número' },
    { code: 'DO', name: 'República Dominicana', flag: '🇩🇴', ddi: '+1-809', placeholder: 'Número' },
    { code: 'CZ', name: 'República Tcheca', flag: '🇨🇿', ddi: '+420', placeholder: 'Número' },
    { code: 'RO', name: 'Romênia', flag: '🇷🇴', ddi: '+40', placeholder: 'Número' },
    { code: 'RW', name: 'Ruanda', flag: '🇷🇼', ddi: '+250', placeholder: 'Número' },
    { code: 'RU', name: 'Rússia', flag: '🇷🇺', ddi: '+7', placeholder: 'Número' },
    { code: 'SB', name: 'Ilhas Salomão', flag: '🇸🇧', ddi: '+677', placeholder: 'Número' },
    { code: 'WS', name: 'Samoa', flag: '🇼🇸', ddi: '+685', placeholder: 'Número' },
    { code: 'SM', name: 'San Marino', flag: '🇸🇲', ddi: '+378', placeholder: 'Número' },
    { code: 'LC', name: 'Santa Lúcia', flag: '🇱🇨', ddi: '+1-758', placeholder: 'Número' },
    { code: 'VC', name: 'São Vicente e Granadinas', flag: '🇻🇨', ddi: '+1-784', placeholder: 'Número' },
    { code: 'ST', name: 'São Tomé e Príncipe', flag: '🇸🇹', ddi: '+239', placeholder: 'Número' },
    { code: 'SN', name: 'Senegal', flag: '🇸🇳', ddi: '+221', placeholder: 'Número' },
    { code: 'SL', name: 'Serra Leoa', flag: '🇸🇱', ddi: '+232', placeholder: 'Número' },
    { code: 'RS', name: 'Sérvia', flag: '🇷🇸', ddi: '+381', placeholder: 'Número' },
    { code: 'SC', name: 'Seychelles', flag: '🇸🇨', ddi: '+248', placeholder: 'Número' },
    { code: 'SG', name: 'Singapura', flag: '🇸🇬', ddi: '+65', placeholder: 'Número' },
    { code: 'SY', name: 'Síria', flag: '🇸🇾', ddi: '+963', placeholder: 'Número' },
    { code: 'SO', name: 'Somália', flag: '🇸🇴', ddi: '+252', placeholder: 'Número' },
    { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', ddi: '+94', placeholder: 'Número' },
    { code: 'SD', name: 'Sudão', flag: '🇸🇩', ddi: '+249', placeholder: 'Número' },
    { code: 'SS', name: 'Sudão do Sul', flag: '🇸🇸', ddi: '+211', placeholder: 'Número' },
    { code: 'SE', name: 'Suécia', flag: '🇸🇪', ddi: '+46', placeholder: 'Número' },
    { code: 'SR', name: 'Suriname', flag: '🇸🇷', ddi: '+597', placeholder: 'Número' },
    { code: 'TJ', name: 'Tajiquistão', flag: '🇹🇯', ddi: '+992', placeholder: 'Número' },
    { code: 'TZ', name: 'Tanzânia', flag: '🇹🇿', ddi: '+255', placeholder: 'Número' },
    { code: 'TH', name: 'Tailândia', flag: '🇹🇭', ddi: '+66', placeholder: 'Número' },
    { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', ddi: '+670', placeholder: 'Número' },
    { code: 'TG', name: 'Togo', flag: '🇹🇬', ddi: '+228', placeholder: 'Número' },
    { code: 'TO', name: 'Tonga', flag: '🇹🇴', ddi: '+676', placeholder: 'Número' },
    { code: 'TT', name: 'Trinidad e Tobago', flag: '🇹🇹', ddi: '+1-868', placeholder: 'Número' },
    { code: 'TN', name: 'Tunísia', flag: '🇹🇳', ddi: '+216', placeholder: 'Número' },
    { code: 'TM', name: 'Turcomenistão', flag: '🇹🇲', ddi: '+993', placeholder: 'Número' },
    { code: 'TR', name: 'Turquia', flag: '🇹🇷', ddi: '+90', placeholder: 'Número' },
    { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', ddi: '+688', placeholder: 'Número' },
    { code: 'UA', name: 'Ucrânia', flag: '🇺🇦', ddi: '+380', placeholder: 'Número' },
    { code: 'UG', name: 'Uganda', flag: '🇺🇬', ddi: '+256', placeholder: 'Número' },
    { code: 'UY', name: 'Uruguai', flag: '🇺🇾', ddi: '+598', placeholder: 'Número' },
    { code: 'UZ', name: 'Uzbequistão', flag: '🇺🇿', ddi: '+998', placeholder: 'Número' },
    { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', ddi: '+678', placeholder: 'Número' },
    { code: 'VA', name: 'Vaticano', flag: '🇻🇦', ddi: '+379', placeholder: 'Número' },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪', ddi: '+58', placeholder: 'Número' },
    { code: 'VN', name: 'Vietnã', flag: '🇻🇳', ddi: '+84', placeholder: 'Número' },
    { code: 'ZM', name: 'Zâmbia', flag: '🇿🇲', ddi: '+260', placeholder: 'Número' },
    { code: 'ZW', name: 'Zimbábue', flag: '🇿🇼', ddi: '+263', placeholder: 'Número' },
];

// Função auxiliar para formatar número de telefone baseado no país
export const formatPhoneNumber = (value: string, countryCode: string): string => {
    // Remove todos os caracteres não numéricos
    const numbers = value.replace(/\D/g, '');

    // Formatação específica para Brasil
    if (countryCode === 'BR') {
        if (numbers.length <= 2) return numbers;
        if (numbers.length <= 6) return `(${numbers.slice(0, 2)}) ${numbers.slice(2)}`;
        if (numbers.length <= 10) return `(${numbers.slice(0, 2)}) ${numbers.slice(2, 6)}-${numbers.slice(6)}`;
        return `(${numbers.slice(0, 2)}) ${numbers.slice(2, 7)}-${numbers.slice(7, 11)}`;
    }

    // Formatação específica para EUA/Canadá
    if (countryCode === 'US' || countryCode === 'CA') {
        if (numbers.length <= 3) return numbers;
        if (numbers.length <= 6) return `(${numbers.slice(0, 3)}) ${numbers.slice(3)}`;
        return `(${numbers.slice(0, 3)}) ${numbers.slice(3, 6)}-${numbers.slice(6, 10)}`;
    }

    // Para outros países, retorna apenas os números sem formatação especial
    return numbers;
};
